/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica5;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author juana
 */
public class Lienzo extends javax.swing.JPanel {
    
    /**
     * Creates new form Lienzo
     */
    private BufferedImage image = null;
    private BufferedImage displayed = null;
    private BufferedImage watermark = null;
    private boolean red = true;
    private boolean blue = true;
    private boolean green = true;
    
    public Lienzo() {
        try {
            image = ImageIO.read(new URL("https://www.todopaisajes.com/1024x768/paseo-por-una-playa-tropical.jpg"));
            displayed = image;
            
            this.setPreferredSize(new Dimension(image.getWidth(),image.getHeight()));
        } catch (MalformedURLException ex) {
            Logger.getLogger(Lienzo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Lienzo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(displayed,0,0,null);
    }
    
    private boolean paint(){
        if(red || green || blue){
            displayed = UtilsPractica5.seleccionarComponentes(image, red, green, blue);
            repaint();
            return true;
        }else{
            return false;
        }
    }
    
    void setRed(){
        red = true;
        paint();
    }
    
    boolean unsetRed() {
        red = false;
        return paint();
    }
    
    void setBlue(){
        blue = true;
        paint();
    }
    
    boolean unsetBlue() {
        blue = false;
        return paint();
    }
    
    void setGreen(){
        green = true;
        paint();
    }
    
    boolean unsetGreen() {
        green = false;
        return paint();
    }
    
    void setAll(){
        red = true;
        blue = true;
        green = true;
        paint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
